package:
  name: pymdmix
  version: 0.2.4

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy

  run:
    - python  {{ python }}
    - numpy
    - scipy
    - biskit
    - matplotlib
    - netcdf4
    - parmed
    - ambertools

about:
  home: http://mdmix.sourceforge.net/
  license: 'https://github.com/CBDD/pyMDmix/blob/master/Licenses/license-mdmix.txt'
  summary: "This is a copy of https://github.com/CBDD/pyMDmix built to be installed with conda."
  description: |
    This is a copy of  https://github.com/CBDD/pyMDmix built to be installed with conda.
    The source code of the project translation from Python 2.7 to 3.7 is https://github.com/dprada/pyMDmix.
  dev_url: https://github.com/CBDD/pyMDmix
  doc_url: http://mdmix.sourceforge.net/
